spring.application.name=mcp

spring.ai.mcp.server.type=SYNC
spring.ai.mcp.server.name=shopping-list-mcp-server
spring.ai.mcp.server.version=1.0.0

mcp.server.url=http://localhost:8081

spring.main.web-application-type=servlet

# Ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2:latest

spring.main.banner-mode=off

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n

logging.file.name=./model-context-protocol/weather/starter-stdio-server/target/mcp-weather-stdio-server.log